"""Centralized simulation defaults shared by CLI/API/scripts."""
from __future__ import annotations

from .types import AttackMode

DEFAULT_RUNS = 200
DEFAULT_NUM_LEGIT = 20
DEFAULT_NUM_REPLAY = 100
DEFAULT_P_LOSS = 0.0
DEFAULT_P_REORDER = 0.0
DEFAULT_WINDOW_SIZE = 5
DEFAULT_MAC_LENGTH = 8
DEFAULT_MAC_TAG_BITS = 80
DEFAULT_SHARED_KEY = "sim_shared_key"
DEFAULT_ATTACKER_RECORD_LOSS = 0.0
DEFAULT_ATTACK_MODE = AttackMode.POST_RUN
DEFAULT_INLINE_ATTACK_PROBABILITY = 0.3
DEFAULT_INLINE_ATTACK_BURST = 1
DEFAULT_CHALLENGE_NONCE_BITS = 32
DEFAULT_MAX_OUTSTANDING_CHALLENGES = 32
DEFAULT_CHALLENGE_TTL_TICKS = 100
